### ISSUE TITLE
can not find exampleData.csv

### ISSUE THREAD

**Issue by kepeng** [nealde/Ampere#9]
I am trying to run 'docs\source\examples\plotting_example.ipynb',but can not find exampleData.csv

**Comment by nealde** [comment]
Sorry for the massive delay - I'll be refactoring this soon. The data is in /data/test_data.csv, but I'll be sure to clean up the examples in the next week or so. I'll message here when it's live

**Comment by nealde** [comment]
The refactor is more or less done - pip installing is more reliable (0.5.5 is the latest version)

If you look at `demo.ipynb` in the root directory, everything should work - let me know if you have any questions!

**Comment by nealde** [comment]
Actually, 0.5.6 addresses a wheel-building issue, so use that one. It reliably works in docker and on windows.
